### ISSUE TITLE
Log file containing fewer rows than LogDataRowCount causes an error

### ISSUE THREAD

**Issue by koele** [vimsh/mafscaling#3]
If a log file contains fewer rows (or results in fewer rows after filtering) than the predefined row count
will result in blank rows at the bottom of the logDataTable. During processing those blank rows cause
an error due to missing data.

**Comment by vimsh** [comment]
sorry, can't read your mind and have no clue what you're talking about... 
1. which tab? 
2. what's the error - is it a pop-up, error in log, or program does process the data?
2. sample log file that causes problem 
3. how to reproduce (step-by-step)?

**Comment by koele** [comment]
1. Load Comp tab, but it likely exists in other tabs as well
2. Error pop-up, screenshot attached msg_error.jpg
    Note: row should be 51, not 501. 
![mafs_error](https://user-images.githubusercontent.com/36203677/35886163-bd7f9cfe-0b55-11e8-8e19-30cd972e95ed.JPG)
3. test_log.zip attached
[test_log.zip](https://github.com/vimsh/mafscaling/files/1700934/test_log.zip)

4. Open MAF Scaling
    Go to Load Comp tab
    Click Load Log and select 'test_log.csv' Click OK, scroll down and note lots of empty lines in the log table
    Paste Current MP Table
    Click GO

Thanks for all your hard work!

**Comment by vimsh** [comment]
Great, thank you!
Just fyi, the row count when you open tab is 200. your file is 47 lines, so all those extra blank rows are fine.
What was missing is a check for those blank rows (Load/IAT Comp were affected), so I added that check and fixed the line numbering.
Changes will be in the next release shortly, just need to finish up a feature request.
