### ISSUE TITLE
Highlight X/Y axis position when viewing 2D/3D graphs

### ISSUE THREAD

**Issue by c360e5f1** [vimsh/mafscaling#4]
Feature suggestion:
1. Freeze the X and Y axis when viewing large tables, so you can quickly tell what column / row you are working in
2. When moving the cursor around with the mouse or keyboard, highlight the X and Y axis label so you can quickly tell what column / row you are working in

**Comment by vimsh** [comment]
1 is not doable, the table is a simple grid where first row/column are used as headers.
2 is doable, maybe at some point when i get a free time on my hands

**Comment by vimsh** [comment]
Added X/Y axis highlighting of active/selected cells
