### ISSUE TITLE
New Play Table Missing

### ISSUE THREAD

**Issue by BCush83** [vimsh/mafscaling#6]
Log View> Log Play when loading certain logs the "Create new table" button is missing

**Comment by vimsh** [comment]
I don't see "Create new table" button in Log Play pop-up, is it "New Play Table" button? Did you check the program log? Please send me your log file(s) that causes the issue so I could check what's going on.

**Comment by BCush83** [comment]
yeah sorry, that's it.  Maybe there is an error in the log I'm
loading...I'm not sure..usually it's next to the Data pulldown but
sometimes it does this and just vanishes...

[image: notableshowing.jpg]

**Comment by vimsh** [comment]
Not sure if you've send the logs, seems like my email fwding doesn't work. If you could put the logs someplace I could grab them from, like a google drive, that'd be great.

**Comment by vimsh** [comment]
If you're ok now, I'll close this issue as I couldn't reproduce it. Otherwise I need your log file.

**Comment by BCush83** [comment]
sorry got tied up...yeah it was a few bad log files, its working now.

**Comment by vimsh** [comment]
Awesome. I'm going to close this thread then. :)
