### ISSUE TITLE
Version 2.7.0 will not run, throws JNI exception; version 2.6.2 works.

### ISSUE THREAD

**Issue by walterstypula** [vimsh/mafscaling#7]
Version 2.7.0 of the application will not start, file maf_scaling.log is not generated.

![image](https://user-images.githubusercontent.com/1973060/132998521-6c7d1836-4b51-4bc9-af48-eb7839268831.png)
![image](https://user-images.githubusercontent.com/1973060/132998665-0cb84a84-adbc-4a57-b9e0-522659338e1f.png)
![image](https://user-images.githubusercontent.com/1973060/132998539-23bb1aad-afdd-43ec-a136-78106937839a.png)
![image](https://user-images.githubusercontent.com/1973060/132998548-091117c0-5e0e-4ee7-8acb-597fedfd9eb4.png)

**Comment by vimsh** [comment]
Version 2.7 requires java 15 or later. Also, note that since Java 9 there is no more JRE, so you have to install JDK.

**Comment by walterstypula** [comment]
I guess I missed that in the notes.

Thanks!

**Comment by vimsh** [comment]
Sorry, my fault, I just added to the notes.
Let me know if all is OK with new Java.
